USE se_course_db;

CREATE TABLE IF NOT EXISTS `user` (
  userEmail VARCHAR(85) NOT NULL PRIMARY KEY,
  userPassword VARCHAR(255) NOT NULL,
  userFirstName VARCHAR(50) NOT NULL,
  userLastName VARCHAR(50) NOT NULL,
  userTel VARCHAR(50) NOT NULL,
  dateOfBirth DATE NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
